version: '3'

services:
  # Postgres container
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_NAME}"
  # Farmers container
  farmer:
    build: .
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db